### ISSUE TITLE
Consistency score.csv en train_V2.csv

### ISSUE THREAD

**Issue by binomaiheu** [Marijkevandesteene/MachineLearning#11]
Mogelijks nuttig ook om es na te gaan of de histogrammen van de feature in score.csv en train_V2.csv min of meer gelijkaardig zijn.

**Comment by Marijkevandesteene** [comment]
In the example solution the score and traning data are 'merged' (without the outcome) are treated in the same way and then divided.
Is that a good approach?

### Use data from the score set for imputing missing values???
To decide on the approach for missing values???

Misschien in ieder geval ook meebekijken, als een van de features in de score lijkt te ontbreken en deze heeft een grote impact in het model, ... heeft dit dan impact op de voorspelling?
je introduceert een fout (guassian fout) bij een voorspelling van een feature / bij imputing a feature.
### MIsschien is het beter een feature niet mee te nemen in het model als deze voor alle te scoren clienten otnbreert

**Comment by binomaiheu** [comment]
bij de imputer opbreken, eerst `.fit()` en dan `.transform()`
