### ISSUE TITLE
Documentation & executive summary

### ISSUE THREAD

**Issue by binomaiheu** [Marijkevandesteene/MachineLearning#12]
@Marijkevandesteene , @dluts, zijn jullie met LaTeX vertrouwd voor het samenwerken aan een rapport / executive summary ? If so, dan kunnen we hier onder `docs` of zo iets opzetten waar we samen tekst  & figuren kunnen in dumpen tijdens de analyse, best om dat en cours de route te doen lijkt me.

**Comment by Marijkevandesteene** [comment]
Voor mij is LaTeX geen probleem, ok om smen te werken aan een document.

**Comment by binomaiheu** [comment]
Ok, voor @dluts is dat ook ok, nog niet veel mee gewerkt, maar zal wel lukken. Zal morgen of zo een docje toevoegen & github action installeren zodat em automatisch pdf genereert telkens bij elke commit.
