### ISSUE TITLE
Categorical/numeric split

### ISSUE THREAD

**Issue by dluts** [Marijkevandesteene/MachineLearning#14]
Currently part of the code is splitting categorical and numeric features based on the 'am' appendix, but that seems a bit too limited too few features are being identified as being numeric.

**Comment by Marijkevandesteene** [comment]
That was left from my initial try outs.
I was still working on the integrated jupyter notebook to make a framework where we could document some of the ideas we had and steps we needed to do / to clear out and fill in as we go.
It was not a 'finished' version. 

But you are right and maybe 'locally' we can better work in python, ...

however that part I still had to remove, ;-)

**Comment by Marijkevandesteene** [comment]
tackled in integrated notebook
