### ISSUE TITLE
Manier van werken met notebooks

### ISSUE THREAD

**Issue by dluts** [Marijkevandesteene/MachineLearning#15]
Omdat notebooks ook de resultaten opslaan krijgen we heel grote git diffs en telkens potentieel merge conflicts die moeilijker te ontwarren zijn dan nodig. Blijven we werken in aparte notebooks die we af en toe integreren? Schakelen we over naar .py die we later naar een notebook omzetten?, ....

**Comment by binomaiheu** [comment]
Ik zou idd aparte notebooks hanteren tot we ergens een geconsolideerde methodiek hebben & die dan integreren in 1 centraal notebook.
