### ISSUE TITLE
Dropping a lot of instances 53 based on missing 'prev_stay'

### ISSUE THREAD

**Issue by dluts** [Marijkevandesteene/MachineLearning#16]
Er worden 53 features gedropt omdat ze missing data hebben voor previous stay, er wordt gezegd dat dit wordt gedaan omdat er heel wat data ontbreekt, maar het is mij niet duidelijk hoe de analyse dit ondersteund.

**Comment by Marijkevandesteene** [comment]
Omdat er heel wat data ontbreekt, leek het me dat deze data al dan niet met ingevulde missing data, kon bijdragen in het trainen van een model. Als u dit vertaalt naar een 3e categorie, misschien wel, te bekijken

**Comment by Marijkevandesteene** [comment]
Niet weerhouden
