### ISSUE TITLE
Hyperparameter - train test split - best percentage

### ISSUE THREAD

**Issue by Marijkevandesteene** [Marijkevandesteene/MachineLearning#28]
What is the optimal percentage for train test split? 20 - 30%?

Learning curve for RF is 
![afbeelding](https://github.com/Marijkevandesteene/MachineLearning/assets/19363349/31f47a16-9ad0-4325-ac35-55c242380a5e)

**Comment by binomaiheu** [comment]
Veel onder de 80 % voor training set (4000 samples) zou ik niet gaan, misschien 75 % / 25 % inderdaad, want in die 5-fold holdout CV gaan er van de trainset nog samples van af.

**Comment by Marijkevandesteene** [comment]
Handled in Final Notebook
