### ISSUE TITLE
Merging changes Dries / Marijke

### ISSUE THREAD

**Issue by Marijkevandesteene** [Marijkevandesteene/MachineLearning#4]
I had been changing the notebook in parallel and with my experience with git (not jupyter notebook, unfortunately) it is difficult to edit document at the same time, therefore I have renamed by notebook.

Yesterday I had also been exploring data and had looked at missing data:
- dropped most frequent missing features (score**)
- dropped instances (53) with missing most features

I had not been looking at dictionary, good tip and thing to consider.

**Comment by Marijkevandesteene** [comment]
As expected I had merge conflicts.

**Comment by dluts** [comment]
Yes, notebooks and git do not go along well, a first look tells me that purely from a code standpoint merging should definitly be possible?

**Comment by Marijkevandesteene** [comment]
Was discussed
Integrated /consolidated notebook and working on own directory
Notebook in git without output/runs

Ik vond dit om Notebook output enkel local te bewaren: https://gist.github.com/33eyes/431e3d432f73371509d176d0dfb95b6e?permalink_comment_id=5065170
