### ISSUE TITLE
Incomplete sentence

### ISSUE THREAD

**Issue by dluts** [Marijkevandesteene/MachineLearning#40]
I found an incomplete sentence, can someone complete it?

 - There seem to be some records which show a total number of nights booked (`nights_booked`) at the chain of 0 ! This is rather surprising given that these

**Comment by binomaiheu** [comment]
Corrected, those are probably new guests, so not so surprising. Adjusted & will upload new PR.

**Comment by Marijkevandesteene** [comment]
I can not find what and how to change and fear conflicts in your changes and my updates in the consolidated notebook. To verify?

**Comment by dluts** [comment]
Adjusted the sentence so it now finishes somewhat correctly for the context.
