### ISSUE TITLE
 Visualisations and exploratory analysis

### ISSUE THREAD

**Issue by dluts** [Marijkevandesteene/MachineLearning#42]
I think we should either discuss the figures in this section or just leave them out.

**Comment by binomaiheu** [comment]
I agree, will put in some explainations of the correlation analysis already. I'm not too sure about the histograms & the 2 scatter plots, but the scatterplot matrix we should select those variables which turned out interesting from the correlation analysis. I'll have a look & complete that section

**Comment by Marijkevandesteene** [comment]
Ok for me.

**Comment by binomaiheu** [comment]
ok, this issue can be close

**Comment by dluts** [comment]
Nicely done!
