### ISSUE TITLE
Applying SMOTE results in negative recall for random forest classifier

### ISSUE THREAD

**Issue by Marijkevandesteene** [Marijkevandesteene/MachineLearning#45]
In consolidating the notebook and applying an oversampling technique to the training data this resulted in a negative recall for damage.

**Comment by Marijkevandesteene** [comment]
While SMOTE can help improve model performance in terms of accuracy, it can sometimes lead to a decrease in recall for the minority class.

This negative impact on recall can occur because SMOTE generates synthetic examples by interpolating between existing minority class instances. As a result, the model may become overly confident in predicting the minority class, leading to more false positives in the predictions and thus reducing the recall for that class.

To mitigate this issue, it's important to carefully evaluate the trade-offs between different performance metrics like recall, precision, and accuracy when using SMOTE. Additionally, tuning the model parameters and considering alternative techniques like adjusting class weights or using more advanced sampling methods may help improve recall without sacrificing other performance metrics.

**Comment by dluts** [comment]
Can be marked as done
