### ISSUE TITLE
Take into account the dictionary - scores

### ISSUE THREAD

**Issue by Marijkevandesteene** [Marijkevandesteene/MachineLearning#5]
As suggested by Dries the dictionary can give information on the features.
A quick look at it indicated that the scores are from different hotels. I believe we can use a mean of the scores per instance and see what that gives.

**Comment by dluts** [comment]
Yes, dropping the scores is not the right approach here, creating a new features containing the score values and information on which hotels have scored seems a bit more sensible to me.

**Comment by Marijkevandesteene** [comment]
Is tackled in the integrated solution
